filebeat.inputs:
  - type: log
    enabled: true
    json.keys_under_root: true
    json.overwrite_keys: true
    paths:
      - /usr/local/var/log/my-shopping-cart/anti-fraud.log
  - type: log
    enabled: true
    json.keys_under_root: true
    json.overwrite_keys: true
    paths:
      - /usr/local/var/log/my-shopping-cart/frontend.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

fields:
  env: staging

output.elasticsearch:
  hosts: ["localhost:9200"]
  protocol: "https"
  ssl.enabled: true
  ssl.verification_mode: none
  username: "elastic"
  password: "elastic"

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

monitoring.enabled: true
monitoring.elasticsearch:
  hosts: ["localhost:9200"]
  protocol: "https"
  ssl.enabled: true
  ssl.verification_mode: none
  username: "elastic"
  password: "elastic"

# Available log levels are: error, warning, info, debug
logging.level: warning

